version: "{branch} {build}"
os: Windows Server 2012
environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0

build:
  verbosity: detailed

build_script:
  - gradlew.bat assemble --info --no-daemon

test_script:
  - gradlew.bat test --info --no-daemon

matrix:
  fast_finish: true
