name: CI
on: [push, pull_request]
jobs:
  gradle:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        java: [1.8]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: check
      - name: Generate Coveralls Test Report
        run: ./gradlew jacocoTestReport coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{secrets.COVERALLS_REPO_TOKEN}}
          CI_NAME: Github Actions
          CI_BRANCH: ${{github.ref}}
          CI_PULL_REQUEST: ${{github.event.pull_request.html_url}}

          